name: style

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check style
      run: cargo fmt --check
